# Generated by Django 5.2.4 on 2025-07-25 10:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Название привычки')),
                ('place', models.CharField(help_text='Введите место для выполнения привычки', max_length=100, verbose_name='Место выполнения привычки')),
                ('date_begin', models.TimeField(blank=True, null=True, verbose_name='Дата начала выполнения')),
                ('action', models.CharField(blank=True, help_text='Введите действие, чтобы обозначить привычку', max_length=140, null=True, verbose_name='Действие для привычки')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Выберите, будет ли привычка приятной.Только приятная привычка будет наградой после выполнения полезной привычки.', verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=7, help_text='Выберите, какая будет периодичность выполнения привычки. По умолчанию ежедневная', verbose_name='Периодичность выполнения привычки')),
                ('award', models.CharField(blank=True, help_text='Введите, чем пользователь должен себя вознаградить после выполнения привычки.', max_length=100, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.DurationField(default=datetime.timedelta(seconds=120), help_text='Введите время, которое потребуется для выполнения привычки. По умолчанию дается 2 минуты', verbose_name='Время, которое потребуется для выполнения привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Привычка находится в публичном доступе')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец привычки')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Выберите привычку, связанную с данной привычкой. Условие: Привычка должна быть полезной.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habit_tracker.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
